# MACD Trend Adaptive Strategy Configuration
# ===========================================
#
# This configuration file controls the behavior of the MACD Trend Adaptive Strategy.
# Each timeframe section contains settings optimized for that specific timeframe.
# The "global" section contains settings that apply to all timeframes unless overridden.

# Global settings (applied to all timeframes)
global:
  # Risk adjustment factors
  counter_trend_factor: 0.5           # Factor applied to ROI for counter-trend trades (lower = take profits sooner)
  aligned_trend_factor: 1.0           # Factor applied to ROI for trend-aligned trades 
  counter_trend_stoploss_factor: 0.5  # Factor applied to stoploss for counter-trend trades (lower = tighter stoploss)
  aligned_trend_stoploss_factor: 1.0  # Factor applied to stoploss for trend-aligned trades
  
  # Strategy behavior settings
  use_dynamic_stoploss: true          # Whether to use dynamic stoploss or static stoploss
  min_win_rate: 0.2                   # Minimum win rate for ROI normalization
  max_win_rate: 0.8                   # Maximum win rate for ROI normalization
  regime_win_rate_diff: 0.2           # Minimum win rate difference to determine market regime
  min_recent_trades_per_direction: 5  # Minimum number of trades required to detect market regime
  max_recent_trades: 10               # Maximum number of recent trades to track for performance metrics
  
  # Other settings
  startup_candle_count: 50            # Number of warmup candles required
  roi_cache_update_interval: 60       # Seconds between ROI cache updates

# 1-minute timeframe configuration
1m:
  # Risk parameters
  risk_reward_ratio: "1:2.5"          # Risk to reward ratio as "1:X" string
  min_stoploss: -0.015                # Closer to zero (tighter stoploss)
  max_stoploss: -0.025                # Further from zero (wider stoploss)

  # MACD signal generation parameters
  macd_preset: "rapid"                # Signal generator (rapid, responsive, classic, conservative, delayed)

  # Trend detection parameters
  adx_threshold: "weak"               # Trend strength detection (slight, weak, moderate, strong, extreme)
  ema_preset: "ultra_short"           # Trend direction detection (ultra_short, short, medium, long, ultra_long)

5m:
  risk_reward_ratio: "1:4"
  min_stoploss: -0.0088
  max_stoploss: -0.0175
  macd_preset: "responsive"
  adx_threshold: "moderate"
  ema_preset: "short"

15m:
  risk_reward_ratio: "1:2.5"
  min_stoploss: -0.02
  max_stoploss: -0.045
  macd_preset: "classic"
  adx_threshold: "moderate"
  ema_preset: "medium"

30m:
  risk_reward_ratio: "1:2.75"
  min_stoploss: -0.0058
  max_stoploss: -0.0138
  macd_preset: "conservative"
  adx_threshold: "moderate"
  ema_preset: "long"

1h:
  risk_reward_ratio: "1:3"
  min_stoploss: -0.0117
  max_stoploss: -0.025
  macd_preset: "conservative"
  adx_threshold: "weak"
  ema_preset: "ultra_long"
